---
site_name: KEEPER
site_url: https://caisr-hh.github.io/keeper/
site_description: Industrial AI research for efficient and predictable operations at Halmstad University.
repo_url: https://github.com/caisr-hh/keeper

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: indigo
    accent: blue
  logo: images/keeper-logo-gradient.svg
  favicon: images/keeper-logo-gradient.png

nav:
  - Home: index.md
  - People: people.md
  - Projects: projects.md
  - Publications: publications.md
  - Partners: partners.md

extra_css:
  - stylesheets/extra.css
